project:
  type: website
  output-dir: docs

website:
  title: "Director Bronkar (U) Limited"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Favourites.qmd

format:
  html:
    theme: sandstone
    mainfont: arial
    fontsize: 1.5rem
    fontcolor: "#0013d5"
    linkcolor: "#ff33f0"
    monofont: courier new
    css: styles.css
    toc: true

editor: visual

